# @package _global_
dataset:
  _target_: src.data.SyntheticCancerDatasetCollection   # Will be dynamically instantiated
  name: tumor_generator
  coeff: ???                                            # Confounding coefficient (gamma)
  chemo_coeff: ${dataset.coeff}                         # Confounding coefficient of chemotherapy
  radio_coeff: ${dataset.coeff}                         # Confounding coefficient of radiotherapy
  seed: ${exp.seed}
  num_patients:
    train: 1000
    val: 1000
    test: 1000
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  obs_coeff: 0.0                                        # Coefficient for observation intensity
  max_intensity: 1.0                                    # Maximum intensity of observation process
  max_seq_length: 30                                    # Max length of time series
  projection_horizon: 1                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1).
                                                        # For GT: hyperparameter tuning done for projection_horizon=0, i.e. tau=1.
  cf_seq_mode: random_trajectories                      # fixed_treatment (/ sliding_treatment / random_trajectories)
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multiclass                            # multiclass / multilabel -- for RMSN
  treatment_sequence: None                 # treatment sequence to train on. Only works if cf_seq_mode = fixed_treatment


model:
  dim_treatments: 4
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 1

exp:
  unscale_rmse: True
  percentage_rmse: True
