# @package _global_
dataset:
  _target_: src.data.MIMIC3SyntheticDatasetCollection      # Will be dynamically instantiated
  seed: ${exp.seed}
  name: mimic3_synthetic
  path: data/processed/all_hourly_data.h5                  # Path with MIMIC-3 dataset (HDFStore)
  min_seq_length: 30                                        # Min sequence length in cohort
  max_seq_length: 50                                       # Max sequence length in cohort
  max_number: 1000                                          # Maximum number of patients in cohort
  data_seed: ${exp.seed}
  projection_horizon: 2                                   # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  n_treatments_seq: 50                                      # Number of random treatments trajectories, sampled for each patient
  split:
    val: 0.2
    test: 0.2
  val_batch_size: 512                                      # Batch size for evaluation
  treatment_mode: multilabel
  treatment_sequence:

  autoregressive: True

  vital_list:
    - heart rate
    - sodium
    - systemic vascular resistance
    - glucose
    - chloride urine
    - blood urea nitrogen
    - bicarbonate
    - magnesium
    - anion gap
  static_list:
    - gender
    - ethnicity
    - age
  drop_first: False                                     # One-hot encoding of categorical static features

  synth_outcomes_list:
    - _target_: src.data.mimic_iii.SyntheticOutcomeGenerator
      exogeneous_vars:
        - heart rate
        - glucose
        - sodium
      exog_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 1.
        scale: 40.0
      exog_weight: 0.9
      endo_dependency:
        _target_: src.data.mimic_iii.utils.DiscretizedRandomGPFunction
        kernels:
          - _target_: sklearn.gaussian_process.kernels.Matern
            length_scale: 25.0
            nu: 2.5
          - _target_: sklearn.gaussian_process.kernels.WhiteKernel
            noise_level: 0.005
      endo_rand_weight: 0.4
      endo_spline_weight: 2.0
      outcome_name: y1

    - _target_: src.data.mimic_iii.SyntheticOutcomeGenerator
      exogeneous_vars:
        - heart rate
        - glucose
        - anion gap
      exog_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 1.
        scale: 40.0
      exog_weight: 1.0
      endo_dependency:
        _target_: src.data.mimic_iii.utils.DiscretizedRandomGPFunction
        kernels:
          - _target_: sklearn.gaussian_process.kernels.Matern
            length_scale: 25.0
            nu: 2.5
          - _target_: sklearn.gaussian_process.kernels.WhiteKernel
            noise_level: 0.001
      endo_rand_weight: 0.5
      endo_spline_weight: 3.5
      outcome_name: y2

  synth_treatments_list:
    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - blood urea nitrogen
        - glucose
        - sodium
      confounder_outcomes:
        - y1
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 1.
        scale: 30.0
      window: 3
      conf_outcome_weight:  0.
      conf_vars_weight: 2.5
      bias: 0.0
      full_effect: -1.0
      effect_window: 1
      treatment_name: t1

    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - systemic vascular resistance
        - bicarbonate
        - anion gap
      confounder_outcomes:
        - y1
        - y2
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 3
        gamma: 1.
        scale: 30.0
      window: 3
      conf_outcome_weight: 0.
      conf_vars_weight: 2.0
      bias: 1.0
      full_effect: -1.0
      effect_window: 1
      treatment_name: t2

    - _target_: src.data.mimic_iii.SyntheticTreatment
      confounding_vars:
        - chloride urine
        - glucose
        - sodium
        - systemic vascular resistance
        - magnesium
        - anion gap
      confounder_outcomes:
        - y2
      confounding_dependency:
        _target_: src.data.mimic_iii.utils.RandomFourierFeaturesFunction
        input_dim: 6
        gamma: 1.
        scale: 30.0
      window: 20
      conf_outcome_weight: 0.
      conf_vars_weight: 1.5
      bias: 0.0
      full_effect: -0.75
      effect_window: 1 #7
      treatment_name: t3

  treatment_outcomes_influence:                                               # dict with treatment-outcomes influences
    y1:
    - t1
    - t2
    - t3
    y2:
    - t1
    - t2
    - t3

exp:
  unscale_rmse: False
  percentage_rmse: False
